### ISSUE TITLE
[GET /user/findById] In user/findById need response - 404 Not found

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/GreenCityProjectStage#267]
**Environment**: Firefox 116.0.3 (64-bit).
Reproducible: always.

**Preconditions**
Sign-in us Admin
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on GET /user/findById
3. Click on 'Try out'
4. Enter invalid data  - (example) id=566

**Actual result**
Align documentation with the real answer
![image](https://github.com/Java-groups/JavaProjectTemplate/assets/128135241/8069419d-75da-4c81-9920-db2856d4edc8)

**Expected result**
404 Not found

**User story and test case links**

**Comment by DenysLiubchenko** [comment]
GET /user/findById returned expected result
