### ISSUE TITLE
[Eco-News, GET/econews/recommended] The 500 (Internal Server Error) response code is returned instead of 400 (Bad Request) code response.

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/GreenCityProjectStage#309]
**Environment:** 
Windows 11 Home
Chrome 114.0.5735.91 (Official buid) (64-bit)
GreenCityDocker-3 is built and running.
**Reproducible:** always.
**Pre-conditions:**
User is not logged in.

**Steps to reproduce**
1.  Select the "Eco-news"controller.
2.  Select the method GET/econews/recommended.
3.  Left "openedEcoNewsId" value field empty.
4.  Pay attention to the response.

**Actual result:** Response code 500 (Internal Server Error) is returned.

**Expected result:** Response code 400 (Bad request) is returned.

**Comment by DenysLiubchenko** [comment]
It returned 400
